# This customization of fig2dev just changes it to use netpbm-octapp instead of netpbm,
# to avoid an svn dependency, which pulls in the large llvm dep, and breaks on macOS
# 10.12.
# See https://github.com/octave-app/octave-app-bundler/issues/76
class Fig2devOctapp < Formula
  desc "Translates figures generated by xfig to other formats"
  homepage "https://mcj.sourceforge.io/"
  url "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
  sha256 "15e246c8d13cc72de25e08314038ad50ce7d2defa9cf1afc172fd7f5932090b1"
  license "MIT"

  keg_only "so it can be installed alongside regular fig2dev"

  depends_on "ghostscript"
  depends_on "libpng"
  depends_on "netpbm-octapp" # octapp change: to avoid pulling in svn and thus llvm

  def install
    args = %W[
      --prefix=#{prefix}
      --disable-dependency-tracking
      --disable-silent-rules
      --enable-transfig
      --without-xpm
      --without-x
    ]

    system "./configure", *args
    system "make", "install"

    # Install a fig file for testing
    pkgshare.install "fig2dev/tests/data/patterns.fig"
  end

  test do
    system "#{bin}/fig2dev", "-L", "png", "#{pkgshare}/patterns.fig", "patterns.png"
    assert_predicate testpath/"patterns.png", :exist?, "Failed to create PNG"
  end
end
